version: '3.9'
services:
  hexaecommerce:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - HEXAC
  test-db:
    image: postgres:13
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - HEXAC
networks:
  HEXAC:
    external: true
